### ISSUE TITLE
Cannot make border for link card

### ISSUE THREAD

**Issue by fuen0015** [fuen0015/link-card#1]
I'm having trouble with the link card, I cannot get a border with the border radius like the screen shot
@thomasjbradley

**Comment by thomasjbradley** [comment]
I don’t see any border or border-radius code in the CSS; what have you tried so far?

**Comment by fuen0015** [comment]
I added a border and border radius to the .link-card class but nothing happens.

**Comment by thomasjbradley** [comment]
The border radius is working but we cannot see it because the `background-color` is on the `<header>` not on the `.link-card`.

The `border` isn’t working because not enough information has been specified to make a border show. Check the Boxes & borders cheat sheet to see what’s necessary for a `border` to show:
https://learn-the-web.algonquindesign.ca/topics/boxes-borders-cheat-sheet/#colours-borders

**Comment by fuen0015** [comment]
I cannot place a bottom border after my list

**Comment by fuen0015** [comment]
I cannot add a bottom border to my list and my button will not center

**Comment by thomasjbradley** [comment]
Have you tried the `border-bottom` CSS property on the `<dl>`?

**Comment by fuen0015** [comment]
I did and nothing happened

**Comment by thomasjbradley** [comment]
I don’t see the attempt in the code—it’s possible it’s because GitHub is still having problems.
Can you paste the code that you wrote?

**Comment by fuen0015** [comment]
dl {
  color: #512200;
  margin: 1em;
  padding: 0;
  padding-bottom: 1em;
  width: 100%
  overflow: hidden;
  border-bottom: 2px;

**Comment by thomasjbradley** [comment]
Borders require 3 pieces of information:

1. The width (which you have)
2. The style: `solid`, `dotted`, etc.
3. The colour

Try this: `border-bottom: 2px solid black`
